
export const SET_USER = "SET_USER";
export const SET_AUTH_STATE_FINISHED = "SET_AUTH_STATE_FINISHED";
export const SET_CURRENT_ERROR = "SET_CURRENT_ERROR";
export const SET_USER_SETUP_CONTENT = "SET_USER_SETUP_CONTENT";
